version: '3'

services:
  app:
    container_name: color-yeezy
    image: ghcr.io/vitorduarte/coloryeezy:main
    env_file: .env
    volumes:
      - ./img:/coloryeezy/img
      - ./config.json/:/coloryeezy/config.json
      - ./tweets.txt:/coloryeezy/tweets.txt
